### ISSUE TITLE
Get error

### ISSUE THREAD

**Issue by chiffacff** [theeraphong0/ESP32Cam_QRCode_Scanner#2]
Hello. I try create QR-reader with ESPino32CAM libs.  I use sketch from example, but get an error:

[E][camera.c:1335] esp_camera_fb_get(): Failed to get the frame on time!

**Comment by theeraphong0** [comment]
> Failed

An error is caused by pin configuration or problem of camera connection form board
if you use same board like me use this library
https://drive.google.com/file/d/1DPcLjx8mj-cjfH721GfC86QY5W9g_5L0/view
